# Github actions workflow called 'GitHub Actions Demo' that triggers on push to main, but not when there are changes to .github folder. On every PR with main as the base branch. Every Sunday at 6:15UTC. Manually.
name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/**
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
# a job called Build that runs on ubuntu-latest and outputs the name of the event that triggered the workflow and outputs the name of the branch the repo is referencing and lists all files in the repo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Print Event Name
        run: |
          echo "Event Name: ${{ github.event_name }}"
      - name: Print Ref
        run: |
          echo "Ref: ${{ github.ref }}"
      - name: List Files
        run: ls -a