# GitHub Action workflow that runs on every push if the action has changed, on manual trigger. Checks out the repoo to reference the action locally.
name: Hello World Docker CI
on:
  push:
    branches:
      - main
    paths:
      - 'hello-world-docker-action/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      - name: Run Docker image
        uses: ./hello-world-docker-action
        with:
          who-to-greet: 'matthew-fiederlein-bzy'

      - name: Print the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"